[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Vite builds to 'dist' by default)
  publish = "dist"

[build.environment]
  # Node version
  NODE_VERSION = "18"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (these will be set in Netlify dashboard)
# VITE_YOUTUBE_API_KEY = "your_api_key_here"
# VITE_MAIN_CHANNEL_ID = "your_channel_id_here"
# VITE_ORIGAMI_PLAYLIST_ID = "your_playlist_id_here"
# VITE_DRAWING_PLAYLIST_ID = "your_playlist_id_here"
# ... (add other playlist IDs as needed)
